-- TRIP

CREATE TABLE TRIP (
TRIP_ID INT NOT NULL,
TRIP_BOOK_TIME DATETIME,
TRIP_START_TIME DATETIME,
TRIP_END_TIME DATETIME,
CUSTOMER_ID INT, -- FK
DRIVER_ID INT, --FK
PAYMENT_ID INT, --FK
FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
PICK_UP_LOCATION_ID INT, --FK
DROP_LOCATION_ID INT, --FK
DISTANCE_TRAVELLED INT, -- CALCULATED
TRIP_DURATION DATETIME, --CALCULATED
TRIP_STATUS VARCHAR(20),
PRIMARY KEY (TRIP_ID)
);


CREATE TABLE PAYMENT (
PAYMENT_ID INT NOT NULL,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
BASE_AMOUNT INT NOT NULL,
TIP_AMOUNT INT,
TOTAL_AMOUNT INT, --CALCULATED
PAYMENT_STATUS VARCHAR(20),
PAYMENT_TIME DATETIME,
PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE LOCATION (
LOCATION_ID INT NOT NULL,
LATITUDE DECIMAL(9,6) NOT NULL,
LONGITUDE DECIMAL(9,6) NOT NULL,
CITY VARCHAR(100) NOT NULL,
STATE VARCHAR(100) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
ZIP_CODE VARCHAR(25),
PRIMARY KEY (LOCATION_ID)
);


