CREATE TABLE LOCATION (
LOCATION_ID INT NOT NULL,
LATITUDE DECIMAL(9,6) NOT NULL,
LONGITUDE DECIMAL(9,6) NOT NULL,
CITY VARCHAR(100) NOT NULL,
STATE VARCHAR(100) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
ZIP_CODE VARCHAR(25),
PRIMARY KEY (LOCATION_ID)
);


