CREATE TABLE PAYMENT (
PAYMENT_ID INT NOT NULL,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
BASE_AMOUNT INT NOT NULL,
TIP_AMOUNT INT,
TOTAL_AMOUNT INT, --CALCULATED
PAYMENT_STATUS VARCHAR(20),
PAYMENT_TIME DATETIME,
PRIMARY KEY (PAYMENT_ID)
);
