CREATE TABLE TRIP (
TRIP_ID INT NOT NULL,
TRIP_BOOK_TIME DATETIME,
TRIP_START_TIME DATETIME,
TRIP_END_TIME DATETIME,
CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
DRIVER_ID INT FOREIGN KEY REFERENCES DRIVER(DRIVER_ID),
PAYMENT_ID INT FOREIGN KEY REFERENCES PAYMENT(PAYMENT_ID),
PICK_UP_LOCATION_ID INT FOREIGN KEY REFERENCES LOCATION(LOCATION_ID),
DROP_OFF_LOCATATION_ID INT FOREIGN KEY REFERENCES LOCATION(LOCATION_ID),
DISTANCE_TRAVELLED INT, -- CALCULATED
TRIP_DURATION DATETIME, --CALCULATED
TRIP_STATUS VARCHAR(20),
PRIMARY KEY (TRIP_ID)
);
